

<!-- this is for login -->
<br><br><br><br><br><br>
<div  class="container">

  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <div class="card-header " style="background-color: #061630; color:gold;">
          <h1 class="card-title   text-white  text-center">
            VISION
          </h1>
        </div>
        <img src="x.jpg">
        <div class="card-body">
          <P class="card-text font-weight-bolder p1">
            Our vision is to be the leading higher educational institution in Nigeria by providing first-rate academic, professional and entrepreneurial education to our students, who are empowered to make a positive impact in the technological and socio-economic development of the country.
          </P>
          
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-header "style="background-color: #061630; color:gold;">
          <h1 class="card-title text-center text-white">
            MISSION
          </h1>
        </div>
        <img src="s.jpg">
        <div class="card-body">

          <ul class="list-group m-5 font-weight-bolder">
              <li class="list-group-items">
              Respect for freedom to associate with any person or group that is recognized by constituted authority.
              </li>
              <li class="list-group-items">
              Regard for Discipline, Loyalty, Honesty, Integrity, Courage and generally acceptable ethical behavior
              </li>
              <li class="list-group-items">
              Regard for lives and property
              </li>
              <li class="list-group-items">
                Proper attitude to work and prudent use of official time, office equipment and facilities
              </li>
              <li class="list-group-items">
                Willingness and respect for the team and team decisions
              </li>
              

              
            </ul>
          
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-header" style="background-color: #061630; color:gold;">
          <h1 class="card-title text-center text-white">
            CORE VALUES
          </h1>
        </div>
        <img src="Sd3.jpg">
        <div class="card-body">
          
                <P class="card-text font-weight-bolder p2">
            Our mission is to produce knowledgeable and innovative graduates, worthy in skill and character, through effective teaching, learning and research for the technological advancement of Nigeria.
          </P>
        </div>
      </div>
    </div>
  </div>
</div>


  









